name: mrwenztest
favicon: null
layout_spectrum: 0.08993635536171496
typography_spectrum: 0.7850706018507481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7412364198826253
  lightness: 0.5243064069654793
  saturation: 0.1885453425347805
  rhythmicContrast: 0.4771397029981017
purpose: []
