name: mrwenztest
favicon: null
layout_spectrum: 0.08993635536171496
typography_spectrum: 0.7850706018507481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#332b28'
    - '#e7b995'
    - '#fefef4'
    - '#9d714e'
  brandStrength: 0.7412364198826253
  lightness: 0.5243064069654793
  saturation: 0.1885453425347805
  rhythmicContrast: 0.4771397029981017
purpose: []
